### ISSUE TITLE
Need to add names for current pre-built images that we offer

### ISSUE THREAD

**Issue by AugieMena3** [ibm-cloud-docs/ibm-spectrum-lsf#1]
In this section:  https://cloud.ibm.com/docs/ibm-spectrum-lsf?topic=ibm-spectrum-lsf-getting-started-tutorial

The first paragraph in Step 3 is currently the following:
"Create a custom image with your OS/LSF and required application binary files. For more information, see Planning for custom images. IBM Cloud provides a pre-built image with CentOS and RHEL and the following packages to get you started quickly. If this list of packages is good enough for your workloads, you do not need to create your own custom image."

We need to include the names of the pre-built images as follows:
""Create a custom image with your OS/LSF and required application binary files. For more information, see Planning for custom images. IBM Cloud provides pre-built images with CentOS and RHEL to help you get started quickly.  The image names for those are hpcc-lsf10-cent77-jun0421-v5 and hpcc-lsf10-rhel77-jun0421-v5, respectively.  In addition to the base operating systems, they also include some commonly used software packages.  If this list of packages is good enough for your workloads, you do not need to create your own custom image."

**Comment by mlgordon** [comment]
Will do.
